In [33]:
import pandas as pd
import numpy as np

In [2]:
import os
os.chdir("..")

In [3]:
from analytics import normalize_nan_str_values

In [29]:
csv_filenames = os.listdir("data/csv")

In [36]:
num_records = {}
counts = {}
for filename in csv_filenames:
    df = pd.read_csv(f"data/csv/{filename}")
    num_records[filename] = df.shape[0]
    for col in df.columns:
        if not col in counts:
            counts[col] = 1
        else:
            counts[col] += 1

In [32]:
len(csv_filenames)

72

In [37]:
print(sum(num_records.values()))
num_records

397450

{'1864.csv': 5174,
 '1887.csv': 7488,
 '1847.csv': 4139,
 '1886.csv': 7412,
 '1874.csv': 6369,
 '1898.csv': 11243,
 '1893.csv': 8191,
 '1894.csv': 8653,
 '1881.csv': 6701,
 '1841.csv': 4114,
 '1844.csv': 4175,
 '1839.csv': 4060,
 '1878.csv': 7205,
 '1896.csv': 9478,
 '1856.csv': 4623,
 '1849.csv': 4201,
 '1866.csv': 5706,
 '1807.csv': 2948,
 '1876.csv': 6896,
 '1865.csv': 5245,
 '1879.csv': 7712,
 '1857.csv': 4538,
 '1859.csv': 4726,
 '1840.csv': 3973,
 '1846.csv': 4405,
 '1895.csv': 9003,
 '1875.csv': 6650,
 '1892.csv': 8337,
 '1853.csv': 4452,
 '1850.csv': 4219,
 '1884.csv': 7528,
 '1863.csv': 5140,
 '1854.csv': 4468,
 '1860.csv': 4773,
 '1880.csv': 7329,
 '1806.csv': 2952,
 '1851.csv': 4242,
 '1813_part2.csv': 2062,
 '1888.csv': 6434,
 '1852.csv': 4393,
 '1897.csv': 10250,
 '1867.csv': 5541,
 '1843.csv': 3939,
 '1810.csv': 2930,
 '1885.csv': 7626,
 '1882.csv': 6868,
 '1889.csv': 6897,
 '1805.csv': 2976,
 '1862.csv': 5007,
 '1871.csv': 6181,
 '1809.csv': 2892,
 '1808.csv': 2755,
 '1891.csv': 8159,
 '1869.csv': 5670,
 '1836.csv': 3999,
 '1877.csv': 7138,
 '1838.csv': 3918,
 '1861.csv': 4879,
 '1848.csv': 4086,
 '1813_part1.csv': 143,
 '1837.csv': 4025,
 '1842.csv': 4149,
 '1872.csv': 6183,
 '1835.csv': 3945,
 '1832.csv': 3674,
 '1868.csv': 5612,
 '1890.csv': 7978,
 '1858.csv': 4606,
 '1845.csv': 4301,
 '1870.csv': 5922,
 '1883.csv': 7549,
 '1873.csv': 6295}

In [31]:
counts

{'nom_rue': 72,
 'nom_rue_htr_corr': 72,
 'nom_rue_norm': 72,
 'no_maison': 72,
 'proprietaire_nom': 59,
 'proprietaire_nom_corr': 57,
 'proprietaire_nom_htr_corr': 59,
 'proprietaire_nom_norm': 59,
 'chef_prenom': 72,
 'chef_prenom_htr_corr': 72,
 'chef_prenom_norm': 72,
 'chef_nom': 72,
 'chef_nom_corr': 69,
 'chef_nom_htr_corr': 72,
 'chef_nom_norm': 72,
 'chef_annee_naissance': 59,
 'epouse_nom': 69,
 'epouse_nom_corr': 66,
 'epouse_nom_htr_corr': 69,
 'epouse_nom_norm': 69,
 'epouse_annee_naissance': 59,
 'enfants_chez_parents_prenom': 36,
 'enfants_chez_parents_prenom_htr_corr': 36,
 'enfants_chez_parents_prenom_norm': 36,
 'enfants_annee_naissance': 52,
 'chef_origine': 72,
 'chef_origine_corr': 69,
 'chef_origine_htr_corr': 72,
 'chef_origine_norm': 72,
 'chef_vocation': 72,
 'chef_vocation_top_terms': 72,
 'chef_vocation_htr_corr': 72,
 'chef_vocation_norm': 72,
 'chef_recepisse': 52,
 'pensionnaires_prenom': 65,
 'pensionnaires_prenom_htr_corr': 65,
 'pensionnaires_prenom_norm': 65,
 'pensionnaires_nom': 65,
 'pensionnaires_nom_corr': 63,
 'pensionnaires_nom_htr_corr': 65,
 'pensionnaires_nom_norm': 65,
 'pensionnaires_annee_naissance': 27,
 'pensionnaires_origine': 65,
 'pensionnaires_origine_corr': 63,
 'pensionnaires_origine_htr_corr': 65,
 'pensionnaires_origine_norm': 65,
 'pensionnaires_condition': 65,
 'pensionnaires_condition_top_terms': 65,
 'pensionnaires_condition_htr_corr': 65,
 'pensionnaires_condition_norm': 65,
 'pensionnaires_recepisse': 52,
 'observations': 72,
 'Page': 72,
 'proprietaire_nom_adresse': 13,
 'proprietaire_nom_adresse_corr': 12,
 'proprietaire_nom_adresse_htr_corr': 13,
 'proprietaire_nom_adresse_norm': 13,
 'chef_date_naissance_1': 2,
 'epouse_prenom': 13,
 'epouse_prenom_htr_corr': 13,
 'epouse_prenom_norm': 13,
 'epouse_date_naissance_1': 2,
 'chef_permis': 13,
 'enfants_date_naissance_1': 2,
 'enfants_profession': 13,
 'enfants_permis': 13,
 'pensionnaires_date_naissance_1': 2,
 'pensionnaires_permis': 13,
 'enfants_dans_la_commune_prenom': 29,
 'enfants_dans_la_commune_prenom_htr_corr': 29,
 'enfants_dans_la_commune_prenom_norm': 29,
 'chef_annee_arrivee': 23,
 'chef_date_naissance_3': 11,
 'epouse_date_naissance_3': 11,
 'enfants_date_naissance_3': 11,
 'pensionnaires_date_naissance_3': 11,
 'fils_prenom': 7,
 'fils_annee_naissance': 7,
 'filles_prenom': 7,
 'filles_annee_naissance': 7,
 'nb_domestiques': 7,
 'nb_ouvriers': 7,
 'nb_pensionnaires': 7,
 'epouse_nom_prenom': 3,
 'epouse_nom_prenom_corr': 3,
 'epouse_nom_prenom_htr_corr': 3,
 'epouse_nom_prenom_norm': 3}

In [5]:
df = pd.read_csv("data/csv/1805.csv")

In [6]:
norm = normalize_nan_str_values(df["no_maison"])

In [7]:
norm

0         1
1       NaN
2       NaN
3        21
4       NaN
       ...
2971    NaN
2972    NaN
2973    NaN
2974      1
2975    NaN
Name: no_maison, Length: 2976, dtype: object

In [46]:
df

,nom_rue,nom_rue_htr_corr,nom_rue_norm,no_maison,proprietaire_nom,proprietaire_nom_corr,proprietaire_nom_htr_corr,proprietaire_nom_norm,chef_prenom,chef_prenom_htr_corr,...,chef_annee_arrivee,chef_vocation,chef_vocation_top_terms,chef_vocation_htr_corr,chef_vocation_norm,nb_domestiques,nb_ouvriers,nb_pensionnaires,observations,Page
0,jn pierre,jn pierre,jean pierre,1,roguerol,roqueirol,roqueirol,roqueirol,damsan,damsan,...,nee,municipal,municipal,municipal,municipal,·,·,2,·,1
1,jn pierre,jn pierre,jean pierre,·,·,·,·,·,veuve de jn francois,veuve de jn francois,...,1754,vis de sesrentes,vis de sesrentes,vis de sesrentes,vis de sesrentes,1,·,·,·,1
2,jn pierre,jn pierre,jean pierre,·,·,·,·,·,francois,francois,...,1799,marchand de for,marchand de for,marchand de for,marchand de for,11,·,·,·,1
3,jn pierre,jn pierre,jean pierre,21,comber,comber,comber,comber,paul henry,paul henry,...,ne|nee,ecrivain,ecrivain,ecrivain,ecrivain,·,·,·,·,1
4,jn pierre,jn pierre,jean pierre,·,·,·,·,·,jean samuel,jean samuel,...,1796,homme de loix,homme de loix,homme de loix,homme de loix,·,2,·,·,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2971,moulin,moulin,moulin,·,martin,martin,martin,martin,jaques,jaques,...,ne,munier,meunier,munier,munier,·,·,·,·,171
2972,moulin,moulin,moulin,·,·,·,·,·,abram louis,abram louis,...,ne|ne,laboureur|laboureur,laboureur|laboureur,laboureur|laboureur,laboureur|laboureur,·,·,·,·,171
2973,sanjalles,sanjalles,sanjalles,·,a la commune,a la commune,a la commune,a la commune,jean jaques,jean jaques,...,·,laboureur,laboureur,laboureur,laboureur,·,·,·,·,171
2974,challet,challet,challet,1,·,·,·,·,jean charles,jean charles,...,ne|ne,laboureur,laboureur,laboureur,laboureur,·,·,·,·,171
2975,enfans,enfans,enfans,·,secretan,secretan,secretan,secretan,loinden da lbinden,loinden da lbinden,...,·,·,·,·,·,·,·,·,·,171

In [51]:
idx_words = df["proprietaire_nom_norm"].str.match("^[a-zA-Z]+( [a-zA-Z]+)*$")
idx_non_words = ~idx_words & (df["proprietaire_nom_norm"] != "·")
df["proprietaire_nom_norm"][idx_non_words]

112      veuve baudes|priquam
128          durcin et|meffat
179           carabet|barelet
239          regamey|chapelli
288       rocheynet|peneveyre
                ...
2662    vitrevert|treyedevant
2669            lortaet|hoirs
2762           hirie de|david
2781          hoisse|sn bierd
2864          koller .|corsat
Name: proprietaire_nom_norm, Length: 71, dtype: object

In [40]:
s = pd.to_numeric(df["no_maison"], errors="coerce")

In [45]:
pd.to_numeric(s.replace(np.nan, -1), downcast="signed")

/home/plouc314/Documents/epfl/ma1/shs/project/.venv/lib/python3.10/site-packages/pandas/core/dtypes/cast.py:377: RuntimeWarning: invalid value encountered in cast
  new_result = trans(result).astype(dtype)

0        1.0
1       -1.0
2       -1.0
3       21.0
4       -1.0
        ...
2971    -1.0
2972    -1.0
2973    -1.0
2974     1.0
2975    -1.0
Name: no_maison, Length: 2976, dtype: float64